VB(NN("hypocrisy") VB("is") JJ(JJ("abhorrent") TO(TO("to") PRP("them"))))
"彼ら" "は" "偽善" "が" "大嫌い" "だ"
VB(PRP("he") VB("has") NN(JJ("unusual") NN("ability")) IN(IN("in") NN("english")))
"彼" "は" "英語" "に" "ずばぬけ" "た" "才能" "を" "持っ" "て" "いる"
VB(PRP("he") VB("was") JJ(JJ("ablaze") IN(IN("with") NN("anger"))))
"彼" "は" "まっ" "赤" "に" "なっ" "て" "おこっ" "て" "い" "た"
VB(PRP("i") VB("abominate") NN("snakes"))
"ヘビ" "が" "大嫌い" "だ"
VB(PRP("i") VB("abominate") VB("dancing"))
"ダンス" "は" "大嫌い" "だ"
VB(NN(DT("the") NN("peak")) VB("rises") IN(IN("above") NN(DT("the") NN("clouds"))))
"その" "峰" "は" "雲の上" "に" "そびえ" "て" "いる"
VB(PRP("he") VB("lives") IN(NN(CD("five") NN("doors")) IN("above") NN(DT("the") NN("school"))))
"彼" "は" "学校" "から" "５" "軒先" "に" "住ん" "で" "いる"
VB(NN(DT("the") NN("news")) VB("got") RB("abroad"))
"その" "情報" "は" "広まっ" "た"
VB(PRP("it") VB("is") JJ(JJ("absurd") TO(TO("to") VB(VB("call") PRP(PRP("him") NN(DT("a") NN("fanatic")))))))
"彼" "を" "狂信" "者" "と" "呼ぶ" "の" "は" "ばかげ" "て" "いる"
MD(PRP("i") MD("cannot") VB(VB("abuse") NN(PRP("their") NN("trust"))))
"彼ら" "の" "信頼" "を" "裏切る" "こと" "は" "私" "に" "は" "でき" "ない"
